name: Manually triggered build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      RUNNING_ON_GITHUB_ACTION: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com/
          scope: '@shareefmorayur'
      - run: yarn install

      - name: Build
        run: yarn build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
